#include "defer.h"
#include "eval.h"

#define PRINT_EXPR(...) #__VA_ARGS__ == |__VA_ARGS__|
#define A() a

PRINT_EXPR()
PRINT_EXPR(_EMPTY())
PRINT_EXPR(PRINT_EXPR(A()))
PRINT_EXPR(DEFER(PRINT_EXPR)(A()))
PRINT_EXPR(DEFER_N(5, PRINT_EXPR)(A()))
PRINT_EXPR(EVAL_1(DEFER(PRINT_EXPR)(A())))
PRINT_EXPR(EVAL_1(DEFER2(PRINT_EXPR)(A())))
PRINT_EXPR(EVAL_1(EVAL_1(DEFER1(PRINT_EXPR)(A()))))
PRINT_EXPR(EVAL_1(EVAL_1(DEFER2(PRINT_EXPR)(A()))))
PRINT_EXPR(EVAL_1(EVAL_1(DEFER3(PRINT_EXPR)(A()))))
PRINT_EXPR(EVAL_1(EVAL_1(DEFER_N(1, PRINT_EXPR)(A()))))
PRINT_EXPR(EVAL_1(EVAL_1(DEFER_N(2, PRINT_EXPR)(A()))))
PRINT_EXPR(EVAL_1(EVAL_1(DEFER_N(3, PRINT_EXPR)(A()))))
PRINT_EXPR(EVAL_1(EVAL_1(DEFER_N(4, PRINT_EXPR)(A()))))
PRINT_EXPR(EVAL_1(EVAL_1(DEFER_N(5, PRINT_EXPR)(A()))))
PRINT_EXPR(EVAL(DEFER1(PRINT_EXPR)(A()))))
PRINT_EXPR(EVAL(DEFER2(PRINT_EXPR)(A()))))
PRINT_EXPR(EVAL(DEFER3(PRINT_EXPR)(A()))))
PRINT_EXPR(EVAL(DEFER_N(1, PRINT_EXPR)(A()))))
PRINT_EXPR(EVAL(DEFER_N(2, PRINT_EXPR)(A()))))
PRINT_EXPR(EVAL(DEFER_N(3, PRINT_EXPR)(A()))))
PRINT_EXPR(EVAL(DEFER_N(4, PRINT_EXPR)(A()))))
PRINT_EXPR(EVAL(DEFER_N(5, PRINT_EXPR)(A()))))

//DEFER(...) __VA_ARGS__ _EMPTY()
//DEFER_N(N, ...) DEFER ## N(__VA_ARGS__)
//DEFER1(...) DEFER(__VA_ARGS__)
//DEFER2(...) __VA_ARGS__ DEFER1(_EMPTY) _EMPTY()
//DEFER3(...) __VA_ARGS__ DEFER1(_EMPTY) _EMPTY()
//DEFER4(...) __VA_ARGS__ DEFER1(_EMPTY) _EMPTY()
//DEFER5(...) __VA_ARGS__ DEFER1(_EMPTY) _EMPTY()
